# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=40)),
                ('g_img', models.CharField(max_length=255)),
                ('g_price', models.CharField(max_length=40)),
                ('g_txt', models.CharField(max_length=255)),
            ],
        ),
    ]
