# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=1, max_length=40)),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.User')),
            ],
        ),
    ]
