# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=1)),
                ('createtime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.Order')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
